
import java.awt.Color;
import java.awt.Dimension;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;


/**
 *
 * @author JHOIMAR
 */
public class V1 extends javax.swing.JFrame {

    /**
     * Creates new form V1
     */
    public V1() {
        initComponents();
        setSize(700, 600); //Defne el ancho y la altura
        setLocationRelativeTo(null); //Coloca el jframe en el centro
        setResizable(false); // No permine modificar el tamaño de la ventana
        setMinimumSize(new Dimension(500,500)); //Estable el tamaño minimo
        getContentPane().setBackground(Color.orange); //Establece un color en el panel
        setDefaultCloseOperation(EXIT_ON_CLOSE); //Deja de ejecutar la aplicación
        setTitle("JUEGO EL AHORCADO");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        btnIntrucciones = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(null);

        btnJugar.setBackground(new java.awt.Color(0, 0, 0));
        btnJugar.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnJugar.setText("JUGAR");
        btnJugar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 3));
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        jPanel2.add(btnJugar);
        btnJugar.setBounds(40, 483, 130, 50);

        btnIntrucciones.setBackground(new java.awt.Color(0, 0, 0));
        btnIntrucciones.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        btnIntrucciones.setForeground(new java.awt.Color(255, 255, 255));
        btnIntrucciones.setText("INSTRUCCIONES");
        btnIntrucciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 3));
        btnIntrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntruccionesActionPerformed(evt);
            }
        });
        jPanel2.add(btnIntrucciones);
        btnIntrucciones.setBounds(200, 480, 310, 50);

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 3));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir);
        btnSalir.setBounds(540, 480, 130, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("src/main/java/Imagenes/Fondo.png"));
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 580);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 700, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        //Abri pre juego
        
        VentanaPre_Juego a = new VentanaPre_Juego();
        a.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Salir
        
        dispose();
        System.exit(0);
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIntruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntruccionesActionPerformed
        // aBRIR INSTRUCCIONES
        V_Instrucciones b = new V_Instrucciones();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIntruccionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIntrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
